_target_: src.datasets.speech_equivalence.make_timit_equivalence_dataset

name: word_broad_10frames
equivalence_classer: word_broad
start_reference: ["fixed", 25]
num_frames_per_phoneme: 10

minimum_frequency_percentile: 10
minimum_frequency_count: 5